image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start LocalStack
    init: localstack start -d

vscode:
  extensions:
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - redhat.vscode-yaml
    - esbenp.prettier-vscode
